name: Supabase CI DEV

on:
  push:
    branches: [dev/**, feature/**]
  pull_request:
    branches: [dev/**, feature/**]
  workflow_dispatch:

jobs:
  test:
    name: Vérification DB (dev)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: supabase/postgres:15.1.0.75
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PostgreSQL client + pgTAP
        run: sudo apt-get update && sudo apt-get install -y postgresql-client postgresql-15-pgtap

      - name: Run FULL presence/structure tests
        run: bash supabase/tests/db/scripts/test_db_profiles_full.sh
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: postgres
          PGDATABASE: postgres
          PGPASSWORD: postgres
