name: Supabase CI STAGING

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
  workflow_dispatch:

jobs:
  db-tests:
    name: Run DB migrations & structure tests (staging)
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          mkdir -p .tmp_supabase_bin
          curl -L https://github.com/supabase/cli/releases/download/v2.33.7/supabase_linux_amd64.tar.gz -o .tmp_supabase_bin/supabase.tar.gz
          tar -xzf .tmp_supabase_bin/supabase.tar.gz -C .tmp_supabase_bin
          chmod +x .tmp_supabase_bin/supabase
          sudo mv .tmp_supabase_bin/supabase /usr/local/bin/supabase

      - name: Vérification Supabase CLI
        run: supabase --version

      - name: Link Supabase STAGING project
        run: supabase link --project-ref lojjhatxyaxxbxiqbuwp  # 🔁 à adapter une fois

      - name: Push latest schema to staging
        run: supabase db push

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client postgresql-15-pgtap

      - name: Run STRUCTURE tests on staging (read-only)
        run: bash supabase/tests/db/scripts/test_db_profiles_structure.sh
        env:
          PGHOST: db.lojjhatxyaxxbxiqbuwp.supabase.co
          PGPORT: 5432
          PGUSER: postgres
          PGDATABASE: postgres
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}

  test-api:
    name: Run REST API tests (staging)
    runs-on: ubuntu-latest
    needs: db-tests
    env:
      SUPABASE_API_URL: https://lojjhatxyaxxbxiqbuwp.supabase.co
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY_STAGING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Run API tests (signup + login + profiles)
        run: bash supabase/tests/api/scripts/run_all_api_tests.sh
