name: Supabase CI – DB tests (staging)

on:
  push:
    branches: [staging, main]     # adapte si besoin
  workflow_dispatch:

env:
  SUPABASE_PROJECT_REF: lojjhatxyaxxbxiqbuwp   # ID de ton projet

jobs:
  db-tests-staging:
    runs-on: ubuntu-latest
    name: Run DB tests on staging
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD_STAGING }}

    steps:
      # 1. Code
      - uses: actions/checkout@v4

      # 2. CLI Supabase
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # 3. Lien vers le projet cloud (sans prompt)
      - name: Link Supabase project (staging)
        run: |
          supabase link \
            --project-ref "$SUPABASE_PROJECT_REF" \
            --password "$SUPABASE_DB_PASSWORD" \
            --yes

      # 4. Push des migrations + seed vers staging
      - name: Push DB schema to staging
        run: supabase db push --linked --yes   # --linked = use project just linked

      # 5. Exporte DB_URL (SSL requis) pour les scripts
      - name: Export DB_URL
        run: |
          echo "DB_URL=postgres://postgres:${SUPABASE_DB_PASSWORD}@db.${SUPABASE_PROJECT_REF}.supabase.co:5432/postgres?sslmode=require" >> "$GITHUB_ENV"

      # 6. Client psql
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      # 7. Tests DB
      - name: Run DB structure tests
        run: |
          bash supabase/tests/db/scripts/test_db_profiles_structure.sh
          bash supabase/tests/db/scripts/test_db_profiles_full.sh
